/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package library;

import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class AdminLogin extends javax.swing.JFrame {

    /**
     * Creates new form AdminLogin
     */
    public AdminLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton3.setBackground(new java.awt.Color(204, 102, 0));
        jButton3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("→");
        jButton3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(520, 0, 50, 30);

        jToggleButton1.setBackground(new java.awt.Color(204, 102, 0));
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library/eye2.png"))); // NOI18N
        jToggleButton1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseClicked(evt);
            }
        });
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jToggleButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jToggleButton1KeyPressed(evt);
            }
        });
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(510, 190, 50, 30);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Admin Login Form");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 30, 220, 28);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library/name.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 90, 40, 40);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library/password.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 180, 40, 40);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter Name :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 90, 150, 40);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter Password :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 180, 170, 40);

        jTextField1.setBackground(new java.awt.Color(204, 102, 0));
        jTextField1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(220, 100, 280, 30);

        jButton1.setBackground(new java.awt.Color(204, 102, 0));
        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library/login.jpg"))); // NOI18N
        jButton1.setText("Login");
        jButton1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(220, 270, 140, 50);

        jPasswordField1.setBackground(new java.awt.Color(204, 102, 0));
        jPasswordField1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(220, 190, 280, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library/admin login.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 570, 360);

        setSize(new java.awt.Dimension(583, 378));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
        String name = jTextField1.getText().trim();
        char pass[] = jPasswordField1.getPassword();
        String parse = String.valueOf(pass);
        if (name.equals("admin")&& parse.equals("1234")){
            new AdminSection().setVisible(true);
            this.setVisible(false);
        }else if(!name.equals("admin")&& !parse.equals("1234")){
            JOptionPane.showMessageDialog(null, "invalid name and password","Invalid",0,  new ImageIcon("R.png"));
        }else if((name.equals("admin")&& !parse.equals("1234"))){
            JOptionPane.showMessageDialog(null, "invalid password","Invalid",0,  new ImageIcon("R.png"));
        }else{
            JOptionPane.showMessageDialog(this, "invalid name","Invalid",0,  new ImageIcon("R.png"));
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new main().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String name = jTextField1.getText().trim();
        char pass[] = jPasswordField1.getPassword();
        String parse = String.valueOf(pass);
        if (name.equals("admin")&& parse.equals("1234")){
            new AdminSection().setVisible(true);
            this.setVisible(false);
        }else if(!name.equals("admin")&& !parse.equals("1234")){
            JOptionPane.showMessageDialog(null, "invalid name and password","Invalid",0,  new ImageIcon("R.png"));
        }else if((name.equals("admin")&& !parse.equals("1234"))){
            JOptionPane.showMessageDialog(null, "invalid password","Invalid",0,  new ImageIcon("R.png"));
        }else{
            JOptionPane.showMessageDialog(this, "invalid name","Invalid",0,  new ImageIcon("R.png"));
        }
        }
    }//GEN-LAST:event_jButton3KeyPressed

    private void jToggleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jToggleButton1MouseClicked

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        if(jToggleButton1.isSelected()){
            jToggleButton1.setIcon(new ImageIcon("eye1.png"));
            jPasswordField1.setEchoChar((char)0);
        }else{
            jToggleButton1.setIcon(new ImageIcon("eye2.png"));
            jPasswordField1.setEchoChar('*');
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String name = jTextField1.getText().trim();
        char pass[] = jPasswordField1.getPassword();
        String parse = String.valueOf(pass);
        if (name.equals("admin")&& parse.equals("1234")){
            new AdminSection().setVisible(true);
            this.setVisible(false);
        }else if(!name.equals("admin")&& !parse.equals("1234")){
            JOptionPane.showMessageDialog(null, "invalid name and password","Invalid",0,  new ImageIcon("R.png"));
        }else if((name.equals("admin")&& !parse.equals("1234"))){
            JOptionPane.showMessageDialog(null, "invalid password","Invalid",0,  new ImageIcon("R.png"));
        }else{
            JOptionPane.showMessageDialog(this, "invalid name","Invalid",0,  new ImageIcon("R.png"));
        }
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String name = jTextField1.getText().trim();
        char pass[] = jPasswordField1.getPassword();
        String parse = String.valueOf(pass);
        if (name.equals("admin")&& parse.equals("1234")){
            new AdminSection().setVisible(true);
            this.setVisible(false);
        }else if(!name.equals("admin")&& !parse.equals("1234")){
            JOptionPane.showMessageDialog(null, "invalid name and password","Invalid",0,  new ImageIcon("R.png"));
        }else if((name.equals("admin")&& !parse.equals("1234"))){
            JOptionPane.showMessageDialog(null, "invalid password","Invalid",0,  new ImageIcon("R.png"));
        }else{
            JOptionPane.showMessageDialog(this, "invalid name","Invalid",0,  new ImageIcon("R.png"));
        }
        }
    }//GEN-LAST:event_jPasswordField1KeyPressed

    private void jToggleButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jToggleButton1KeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String name = jTextField1.getText().trim();
        char pass[] = jPasswordField1.getPassword();
        String parse = String.valueOf(pass);
        if (name.equals("admin")&& parse.equals("1234")){
            new AdminSection().setVisible(true);
            this.setVisible(false);
        }else if(!name.equals("admin")&& !parse.equals("1234")){
            JOptionPane.showMessageDialog(null, "invalid name and password","Invalid",0,  new ImageIcon("R.png"));
        }else if((name.equals("admin")&& !parse.equals("1234"))){
            JOptionPane.showMessageDialog(null, "invalid password","Invalid",0,  new ImageIcon("R.png"));
        }else{
            JOptionPane.showMessageDialog(this, "invalid name","Invalid",0,  new ImageIcon("R.png"));
        }
        }
    }//GEN-LAST:event_jToggleButton1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
