/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package adhamcocacolavm;

import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class buyingFrame extends javax.swing.JFrame {
//global variables
//===============

    int numberOfCola = 0;
    int numberOfFanta = 0;
    int numberOfSprite = 0;
    int numberOfMaxCola = 0;
    int numberOfSinacolaOrange = 0;
    int numberOfSinacolaApple = 0;
    int numberOfSinacolaCoca = 0;
    int numberOfFayrouz = 0;

    //check if money is 5,10,50,100,200 or no
    //========================================
    public static void Money(int numberOfFanta, int numberOfSprite, int numberOfSinacolaCoca, int numberOfSinacolaApple, int numberOfMaxCola, int numberOfCola, int numberOfSinacolaOrange, int numberOfFayrouz, int totalPrice) {
        String Money = JOptionPane.showInputDialog(null, "please put your money ", "PUT money", 3);
        int parseMoney = Integer.parseInt(Money);

        if (parseMoney == 5 || parseMoney == 10 || parseMoney == 50 || parseMoney == 100 || parseMoney == 200) {
            //recet 
            //=====
            JOptionPane.showMessageDialog(null, "type                  number                  price "
                    + "\ncocacola                  " + numberOfCola + "                      " + numberOfCola * 10 + "EGP"
                    + "\nfanta                     " + numberOfFanta + "                      " + numberOfFanta * 10 + "EGP"
                    + "\nsprite                    " + numberOfSprite + "                      " + numberOfSprite * 10 + "EGP "
                    + "\nsinacola coca       " + numberOfSinacolaCoca + "                        " + numberOfSinacolaCoca * 5 + "EGP "
                    + "\nsinacola apple      " + numberOfSinacolaApple + "                        " + numberOfSinacolaApple * 5 + "EGP "
                    + "\nmax cola               " + numberOfMaxCola + "                      " + numberOfMaxCola * 10 + "EGP "
                    + "\nsinacola orange    " + numberOfSinacolaOrange + "                        " + numberOfSinacolaOrange * 5 + "EGP "
                    + "\nfayrouz                  " + numberOfFayrouz + "                      " + numberOfFayrouz * 10 + "EGP "
                    + "\ntotal :                                            " + totalPrice + "EGP"
                    + "\namount paid :                              " + parseMoney + "EGP"
                    + "\nrest :                                           " + (parseMoney - totalPrice) + "EGP");
            return;
        } else if (parseMoney != 5 || parseMoney != 10 || parseMoney != 50 || parseMoney != 100 || parseMoney != 200) {
            JOptionPane.showMessageDialog(null, "must enter this money only (5,10,50,100,200)");
            Money(numberOfFanta, numberOfSprite, numberOfSinacolaCoca, numberOfSinacolaApple, numberOfMaxCola, numberOfCola, numberOfSinacolaOrange, numberOfFayrouz, totalPrice);
        } else {
        }
    }

    public buyingFrame() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        done = new javax.swing.JButton();
        cocacola = new javax.swing.JToggleButton();
        fanta = new javax.swing.JToggleButton();
        sinacolaCoca = new javax.swing.JToggleButton();
        sinacolaApple = new javax.swing.JToggleButton();
        maxCola = new javax.swing.JToggleButton();
        sinacolaOrange = new javax.swing.JToggleButton();
        fayrouz = new javax.swing.JToggleButton();
        sprite = new javax.swing.JToggleButton();
        backToMain = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jComboBox1.setBackground(new java.awt.Color(255, 0, 0));
        jComboBox1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "QUANTATY", "1", "2", "3", "Other" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(60, 230, 150, 30);

        done.setBackground(new java.awt.Color(0, 0, 0));
        done.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        done.setForeground(new java.awt.Color(255, 51, 51));
        done.setText("DONE");
        done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneActionPerformed(evt);
            }
        });
        getContentPane().add(done);
        done.setBounds(290, 350, 170, 40);

        cocacola.setBackground(new java.awt.Color(255, 51, 51));
        cocacola.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cocacola.setText("COCA COLA  10EGP");
        cocacola.setAutoscrolls(true);
        cocacola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cocacolaMouseClicked(evt);
            }
        });
        cocacola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cocacolaActionPerformed(evt);
            }
        });
        getContentPane().add(cocacola);
        cocacola.setBounds(10, 140, 170, 30);

        fanta.setBackground(new java.awt.Color(255, 153, 0));
        fanta.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        fanta.setText("FANTA  10EGP");
        fanta.setAutoscrolls(true);
        fanta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fantaMouseClicked(evt);
            }
        });
        getContentPane().add(fanta);
        fanta.setBounds(180, 140, 130, 30);

        sinacolaCoca.setBackground(new java.awt.Color(255, 51, 51));
        sinacolaCoca.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        sinacolaCoca.setText("SINACOLA COCA  5EGP");
        sinacolaCoca.setAutoscrolls(true);
        sinacolaCoca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sinacolaCocaMouseClicked(evt);
            }
        });
        getContentPane().add(sinacolaCoca);
        sinacolaCoca.setBounds(310, 140, 200, 30);

        sinacolaApple.setBackground(new java.awt.Color(0, 255, 102));
        sinacolaApple.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        sinacolaApple.setText("SINACOLA APPLE  5EGP");
        sinacolaApple.setAutoscrolls(true);
        sinacolaApple.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sinacolaAppleMouseClicked(evt);
            }
        });
        getContentPane().add(sinacolaApple);
        sinacolaApple.setBounds(510, 140, 200, 30);

        maxCola.setBackground(new java.awt.Color(255, 51, 51));
        maxCola.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        maxCola.setText("MAX COLA  10EGP");
        maxCola.setAutoscrolls(true);
        maxCola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maxColaMouseClicked(evt);
            }
        });
        maxCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxColaActionPerformed(evt);
            }
        });
        getContentPane().add(maxCola);
        maxCola.setBounds(10, 170, 170, 30);

        sinacolaOrange.setBackground(new java.awt.Color(255, 153, 0));
        sinacolaOrange.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        sinacolaOrange.setText("SINACOLA ORANGE  5EGP");
        sinacolaOrange.setAutoscrolls(true);
        sinacolaOrange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sinacolaOrangeMouseClicked(evt);
            }
        });
        sinacolaOrange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinacolaOrangeActionPerformed(evt);
            }
        });
        getContentPane().add(sinacolaOrange);
        sinacolaOrange.setBounds(180, 170, 220, 30);

        fayrouz.setBackground(new java.awt.Color(255, 102, 0));
        fayrouz.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        fayrouz.setText("FAYROUZ  10EGP");
        fayrouz.setAutoscrolls(true);
        fayrouz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fayrouzMouseClicked(evt);
            }
        });
        getContentPane().add(fayrouz);
        fayrouz.setBounds(400, 170, 170, 30);

        sprite.setBackground(new java.awt.Color(204, 255, 204));
        sprite.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        sprite.setText("SPRITE  10EGP");
        sprite.setAutoscrolls(true);
        sprite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spriteMouseClicked(evt);
            }
        });
        getContentPane().add(sprite);
        sprite.setBounds(570, 170, 140, 30);

        backToMain.setBackground(new java.awt.Color(0, 0, 0));
        backToMain.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        backToMain.setForeground(new java.awt.Color(255, 51, 51));
        backToMain.setText("BACK TO START");
        backToMain.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        backToMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMainActionPerformed(evt);
            }
        });
        getContentPane().add(backToMain);
        backToMain.setBounds(30, 430, 190, 40);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adhamcocacolavm/mdham.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 720, 500);

        setSize(new java.awt.Dimension(734, 527));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneActionPerformed
// check if you want choose another types in one recet
//=====================================================
        Object ob2[] = new String[2];
        ob2[0] = "YES";
        ob2[1] = "NO";
        int yesOrNo = JOptionPane.showOptionDialog(null, "Do you want to choose other types ?", "CHOISE", 0, 3, null, ob2, null);
        if (yesOrNo == 0) {
            this.setVisible(true);

            cocacola.setEnabled(true);
            sinacolaApple.setEnabled(true);
            sinacolaCoca.setEnabled(true);
            sinacolaOrange.setEnabled(true);
            maxCola.setEnabled(true);
            fayrouz.setEnabled(true);
            sprite.setEnabled(true);
            fanta.setEnabled(true);

            jComboBox1.setSelectedIndex(0);//return jcombo box to quantaty

        } else {
            this.setVisible(false);
            String Money = JOptionPane.showInputDialog(null, "please put your money ", "PUT money", 3);

            try {
                if (Money.equals("null")) {

                }
            } catch (NullPointerException  ex) {
                Main m = new Main();
                m.setVisible(true);
                this.setVisible(false);
            }
            int parseMoney = Integer.parseInt(Money);

            int totalPrice = (numberOfCola * 10) + (numberOfFanta * 10) + (numberOfSprite * 10) + (numberOfSinacolaCoca * 5) + (numberOfSinacolaApple * 5) + (numberOfSinacolaOrange * 5) + (numberOfFayrouz * 10) + (numberOfMaxCola * 10);

            if (parseMoney == 5 || parseMoney == 10 || parseMoney == 50 || parseMoney == 100 || parseMoney == 200) {
                //recet
                //=====
                JOptionPane.showMessageDialog(null, "type                  number                  price "
                        + "\ncocacola                " + numberOfCola + "                      " + numberOfCola * 10 + "EGP"
                        + "\nfanta                      " + numberOfFanta + "                      " + numberOfFanta * 10 + "EGP"
                        + "\nsprite                     " + numberOfSprite + "                      " + numberOfSprite * 10 + "EGP "
                        + "\nsinacola coca        " + numberOfSinacolaCoca + "                      " + numberOfSinacolaCoca * 5 + "EGP "
                        + "\nsinacola apple       " + numberOfSinacolaApple + "                      " + numberOfSinacolaApple * 5 + "EGP "
                        + "\nmax cola                " + numberOfMaxCola + "                      " + numberOfMaxCola * 10 + "EGP "
                        + "\nsinacola orange     " + numberOfSinacolaOrange + "                     " + numberOfSinacolaOrange * 5 + "EGP "
                        + "\nfayrouz                   " + numberOfFayrouz + "                     " + numberOfFayrouz * 10 + "EGP "
                        + "\ntotal :                                             " + totalPrice + "EGP"
                        + "\namount paid :                            " + parseMoney + "EGP"
                        + "\nrest :                                          " + (parseMoney - totalPrice) + "EGP");
                JOptionPane.showMessageDialog(null, "thank you for coming this machine");
                return;
            } else {
                JOptionPane.showMessageDialog(null, "must enter this money only (5,10,50,100,200)");
                Money(numberOfFanta, numberOfSprite, numberOfSinacolaCoca, numberOfSinacolaApple, numberOfMaxCola, numberOfCola, numberOfSinacolaOrange, numberOfFayrouz, totalPrice);
            }
        }


    }//GEN-LAST:event_doneActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // choose the quantaty
        //====================

        Object o = jComboBox1.getItemAt(jComboBox1.getSelectedIndex());//return item selected index then convert index to item

        int quantatyCocacola = 10;//initial value to cocacola

        if (cocacola.isEnabled()) {//check if cocacola button is enabled or no 

            if (o.equals("Other")) {
                String quantaty = JOptionPane.showInputDialog(null, "enter the quantaty", "ENTER", 3);
                int parseQuantaty = Integer.parseInt(quantaty);
                if (parseQuantaty > quantatyCocacola) {
                    JOptionPane.showMessageDialog(null, "Sorry, there are not enough of this type");

                    cocacola.setEnabled(true);
                    sinacolaApple.setEnabled(true);
                    sinacolaCoca.setEnabled(true);
                    sinacolaOrange.setEnabled(true);
                    maxCola.setEnabled(true);
                    fayrouz.setEnabled(true);
                    sprite.setEnabled(true);
                    fanta.setEnabled(true);
                    parseQuantaty = 0;
                    jComboBox1.setSelectedIndex(0);

                } else {
                    quantatyCocacola -= parseQuantaty;

                }
                numberOfCola += parseQuantaty;//number of cola buyed

            } else if (o.equals("1")) {
                quantatyCocacola -= 1;

                if (quantatyCocacola == 0) {
                    cocacola.setEnabled(false);
                } else {
                    cocacola.setEnabled(true);

                }
                numberOfCola++;

            } else if (o.equals("2")) {
                numberOfCola += 2;

            } else if (o.equals("3")) {
                numberOfCola += 3;

            }
        } else if (fanta.isEnabled()) {
            int quantatyFanta = 10;

            if (o.equals("Other")) {
                String quantaty = JOptionPane.showInputDialog(null, "enter the quantaty", "ENTER", 3);
                int parseQuantaty = Integer.parseInt(quantaty);

                if (parseQuantaty > quantatyCocacola) {
                    JOptionPane.showMessageDialog(null, "Sorry, there are not enough of this type");

                    cocacola.setEnabled(true);
                    sinacolaApple.setEnabled(true);
                    sinacolaCoca.setEnabled(true);
                    sinacolaOrange.setEnabled(true);
                    maxCola.setEnabled(true);
                    fayrouz.setEnabled(true);
                    sprite.setEnabled(true);
                    fanta.setEnabled(true);
                    parseQuantaty = 0;
                    jComboBox1.setSelectedIndex(0);

                } else {
                    quantatyFanta -= parseQuantaty;
                }

                numberOfFanta += parseQuantaty;

            } else if (o.equals("1")) {
                numberOfFanta++;

            } else if (o.equals("2")) {
                numberOfFanta += 2;

            } else if (o.equals("3")) {
                numberOfFanta += 3;

            }
        } else if (sinacolaCoca.isEnabled()) {
            int quantatySinacolaCoca = 10;

            if (o.equals("Other")) {
                String quantaty = JOptionPane.showInputDialog(null, "enter the quantaty", "ENTER", 3);
                int parseQuantaty = Integer.parseInt(quantaty);

                if (parseQuantaty > quantatySinacolaCoca) {
                    JOptionPane.showMessageDialog(null, "Sorry, there are not enough of this type");

                    cocacola.setEnabled(true);
                    sinacolaApple.setEnabled(true);
                    sinacolaCoca.setEnabled(true);
                    sinacolaOrange.setEnabled(true);
                    maxCola.setEnabled(true);
                    fayrouz.setEnabled(true);
                    sprite.setEnabled(true);
                    fanta.setEnabled(true);
                    parseQuantaty = 0;
                    jComboBox1.setSelectedIndex(0);

                } else {
                    quantatySinacolaCoca -= parseQuantaty;
                }
                numberOfSinacolaCoca += parseQuantaty;

            } else if (o.equals("1")) {
                numberOfSinacolaCoca++;

            } else if (o.equals("2")) {
                numberOfSinacolaCoca += 2;

            } else if (o.equals("3")) {
                numberOfSinacolaCoca += 3;

            }
        } else if (sinacolaApple.isEnabled()) {

            int quantatySinacolaApple = 10;

            if (o.equals("Other")) {
                String quantaty = JOptionPane.showInputDialog(null, "enter the quantaty", "ENTER", 3);
                int parseQuantaty = Integer.parseInt(quantaty);

                if (parseQuantaty > quantatySinacolaApple) {
                    JOptionPane.showMessageDialog(null, "Sorry, there are not enough of this type");

                    cocacola.setEnabled(true);
                    sinacolaApple.setEnabled(true);
                    sinacolaCoca.setEnabled(true);
                    sinacolaOrange.setEnabled(true);
                    maxCola.setEnabled(true);
                    fayrouz.setEnabled(true);
                    sprite.setEnabled(true);
                    fanta.setEnabled(true);
                    parseQuantaty = 0;
                    jComboBox1.setSelectedIndex(0);

                } else {
                    quantatySinacolaApple -= parseQuantaty;
                }
                numberOfSinacolaApple += parseQuantaty;

            } else if (o.equals("1")) {
                numberOfSinacolaApple++;

            } else if (o.equals("2")) {
                numberOfSinacolaApple += 2;

            } else if (o.equals("3")) {
                numberOfSinacolaApple += 3;

            }
        } else if (maxCola.isEnabled()) {

            int quantatyMaxCola = 10;

            if (o.equals("Other")) {
                String quantaty = JOptionPane.showInputDialog(null, "enter the quantaty", "ENTER", 3);
                int parseQuantaty = Integer.parseInt(quantaty);

                if (parseQuantaty > quantatyMaxCola) {
                    JOptionPane.showMessageDialog(null, "Sorry, there are not enough of this type");

                    cocacola.setEnabled(true);
                    sinacolaApple.setEnabled(true);
                    sinacolaCoca.setEnabled(true);
                    sinacolaOrange.setEnabled(true);
                    maxCola.setEnabled(true);
                    fayrouz.setEnabled(true);
                    sprite.setEnabled(true);
                    fanta.setEnabled(true);
                    parseQuantaty = 0;
                    jComboBox1.setSelectedIndex(0);

                } else {
                    quantatyMaxCola -= parseQuantaty;
                }
                numberOfMaxCola += parseQuantaty;

            } else if (o.equals("1")) {
                numberOfMaxCola++;

            } else if (o.equals("2")) {
                numberOfMaxCola += 2;

            } else if (o.equals("3")) {
                numberOfMaxCola += 3;

            }
        } else if (sinacolaOrange.isEnabled()) {

            int quantatySinacolaOrange = 10;

            if (o.equals("Other")) {
                String quantaty = JOptionPane.showInputDialog(null, "enter the quantaty", "ENTER", 3);
                int parseQuantaty = Integer.parseInt(quantaty);

                if (parseQuantaty > quantatySinacolaOrange) {
                    JOptionPane.showMessageDialog(null, "Sorry, there are not enough of this type");

                    cocacola.setEnabled(true);
                    sinacolaApple.setEnabled(true);
                    sinacolaCoca.setEnabled(true);
                    sinacolaOrange.setEnabled(true);
                    maxCola.setEnabled(true);
                    fayrouz.setEnabled(true);
                    sprite.setEnabled(true);
                    fanta.setEnabled(true);
                    parseQuantaty = 0;
                    jComboBox1.setSelectedIndex(0);

                } else {
                    quantatySinacolaOrange -= parseQuantaty;
                }
                numberOfSinacolaOrange += parseQuantaty;

            } else if (o.equals("1")) {
                numberOfSinacolaOrange++;

            } else if (o.equals("2")) {
                numberOfSinacolaOrange += 2;

            } else if (o.equals("3")) {
                numberOfSinacolaOrange += 3;

            }
        } else if (fayrouz.isEnabled()) {

            int quantatyFayrouz = 10;

            if (o.equals("Other")) {
                String quantaty = JOptionPane.showInputDialog(null, "enter the quantaty", "ENTER", 3);
                int parseQuantaty = Integer.parseInt(quantaty);

                if (parseQuantaty > quantatyFayrouz) {
                    JOptionPane.showMessageDialog(null, "Sorry, there are not enough of this type");

                    cocacola.setEnabled(true);
                    sinacolaApple.setEnabled(true);
                    sinacolaCoca.setEnabled(true);
                    sinacolaOrange.setEnabled(true);
                    maxCola.setEnabled(true);
                    fayrouz.setEnabled(true);
                    sprite.setEnabled(true);
                    fanta.setEnabled(true);
                    parseQuantaty = 0;
                    jComboBox1.setSelectedIndex(0);

                } else {
                    quantatyFayrouz -= parseQuantaty;
                }
                numberOfFayrouz += parseQuantaty;

            } else if (o.equals("1")) {
                numberOfFayrouz++;

            } else if (o.equals("2")) {
                numberOfFayrouz += 2;

            } else if (o.equals("3")) {
                numberOfFayrouz += 3;

            }
        } else if (sprite.isEnabled()) {

            int quantatySprite = 10;

            if (o.equals("Other")) {
                String quantaty = JOptionPane.showInputDialog(null, "enter the quantaty", "ENTER", 3);
                int parseQuantaty = Integer.parseInt(quantaty);

                if (parseQuantaty > quantatySprite) {
                    JOptionPane.showMessageDialog(null, "Sorry, there are not enough of this type");

                    cocacola.setEnabled(true);
                    sinacolaApple.setEnabled(true);
                    sinacolaCoca.setEnabled(true);
                    sinacolaOrange.setEnabled(true);
                    maxCola.setEnabled(true);
                    fayrouz.setEnabled(true);
                    sprite.setEnabled(true);
                    fanta.setEnabled(true);
                    parseQuantaty = 0;
                    jComboBox1.setSelectedIndex(0);

                } else {
                    quantatySprite -= parseQuantaty;
                }
                numberOfSprite += parseQuantaty;

            } else if (o.equals("1")) {
                numberOfSprite++;

            } else if (o.equals("2")) {
                numberOfSprite += 2;

            } else if (o.equals("3")) {
                numberOfSprite += 3;

            }
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void sinacolaOrangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinacolaOrangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sinacolaOrangeActionPerformed

    private void cocacolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cocacolaActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_cocacolaActionPerformed

    private void cocacolaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cocacolaMouseClicked
        /*
        if click the cocacola all another items closed because
        user does not choose any item in the same time but 
        avalible to choose another items in one recet
         */
        fanta.setEnabled(false);
        sinacolaApple.setEnabled(false);
        sinacolaCoca.setEnabled(false);
        sinacolaOrange.setEnabled(false);
        maxCola.setEnabled(false);
        fayrouz.setEnabled(false);
        sprite.setEnabled(false);

        Object o = jComboBox1.getItemAt(jComboBox1.getSelectedIndex());

        if (o.equals("Other")) {

            String quantaty = JOptionPane.showInputDialog(null, "enter the quantaty", "ENTER", 3);
            int parseQuantaty = Integer.parseInt(quantaty);

            numberOfCola += parseQuantaty;
        } else if (o.equals("1")) {
            numberOfCola++;

        } else if (o.equals("2")) {
            numberOfCola += 2;

        } else if (o.equals("3")) {
            numberOfCola += 3;

        }

    }//GEN-LAST:event_cocacolaMouseClicked

    private void fantaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fantaMouseClicked
        // TODO add your handling code here:

        cocacola.setEnabled(false);
        sinacolaApple.setEnabled(false);
        sinacolaCoca.setEnabled(false);
        sinacolaOrange.setEnabled(false);
        maxCola.setEnabled(false);
        fayrouz.setEnabled(false);
        sprite.setEnabled(false);

        Object o = jComboBox1.getItemAt(jComboBox1.getSelectedIndex());

        if (o.equals("Other")) {
            String quantaty = JOptionPane.showInputDialog(null, "enter the quantaty", "ENTER", 3);
            int parseQuantaty = Integer.parseInt(quantaty);

            numberOfFanta += parseQuantaty;

        } else if (o.equals("1")) {

            numberOfFanta++;

        } else if (o.equals("2")) {

            numberOfFanta += 2;

        } else if (o.equals("3")) {
            numberOfFanta += 3;

        }
    }//GEN-LAST:event_fantaMouseClicked

    private void sinacolaCocaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sinacolaCocaMouseClicked
        // TODO add your handling code here:
        cocacola.setEnabled(false);
        sinacolaApple.setEnabled(false);
        fanta.setEnabled(false);
        sinacolaOrange.setEnabled(false);
        maxCola.setEnabled(false);
        fayrouz.setEnabled(false);
        sprite.setEnabled(false);

        Object o = jComboBox1.getItemAt(jComboBox1.getSelectedIndex());

        if (o.equals("Other")) {
            String quantaty = JOptionPane.showInputDialog(null, "enter the quantaty", "ENTER", 3);
            int parseQuantaty = Integer.parseInt(quantaty);

            numberOfSinacolaCoca += parseQuantaty;

        } else if (o.equals("1")) {

            numberOfSinacolaCoca++;

        } else if (o.equals("2")) {
            numberOfSinacolaCoca += 2;

        } else if (o.equals("3")) {
            numberOfSinacolaCoca += 3;

        }
    }//GEN-LAST:event_sinacolaCocaMouseClicked

    private void sinacolaAppleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sinacolaAppleMouseClicked
        // TODO add your handling code here:
        cocacola.setEnabled(false);
        sinacolaCoca.setEnabled(false);
        fanta.setEnabled(false);
        sinacolaOrange.setEnabled(false);
        maxCola.setEnabled(false);
        fayrouz.setEnabled(false);
        sprite.setEnabled(false);

        Object o = jComboBox1.getItemAt(jComboBox1.getSelectedIndex());

        if (o.equals("Other")) {
            String quantaty = JOptionPane.showInputDialog(null, "enter the quantaty", "ENTER", 3);
            int parseQuantaty = Integer.parseInt(quantaty);

            numberOfSinacolaApple += parseQuantaty;

        } else if (o.equals("1")) {
            numberOfSinacolaApple++;

        } else if (o.equals("2")) {
            numberOfSinacolaApple += 2;

        } else if (o.equals("3")) {
            numberOfSinacolaApple += 3;

        }
    }//GEN-LAST:event_sinacolaAppleMouseClicked

    private void maxColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxColaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxColaActionPerformed

    private void maxColaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxColaMouseClicked
        // TODO add your handling code here:
        cocacola.setEnabled(false);
        sinacolaCoca.setEnabled(false);
        fanta.setEnabled(false);
        sinacolaOrange.setEnabled(false);
        sinacolaApple.setEnabled(false);
        fayrouz.setEnabled(false);
        sprite.setEnabled(false);

        Object o = jComboBox1.getItemAt(jComboBox1.getSelectedIndex());

        if (o.equals("Other")) {
            String quantaty = JOptionPane.showInputDialog(null, "enter the quantaty", "ENTER", 3);
            int parseQuantaty = Integer.parseInt(quantaty);

            numberOfMaxCola += parseQuantaty;

        } else if (o.equals("1")) {
            numberOfMaxCola++;

        } else if (o.equals("2")) {
            numberOfMaxCola += 2;

        } else if (o.equals("3")) {
            numberOfMaxCola += 3;

        }
    }//GEN-LAST:event_maxColaMouseClicked

    private void sinacolaOrangeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sinacolaOrangeMouseClicked
        // TODO add your handling code here:
        cocacola.setEnabled(false);
        sinacolaCoca.setEnabled(false);
        fanta.setEnabled(false);
        maxCola.setEnabled(false);
        sinacolaApple.setEnabled(false);
        fayrouz.setEnabled(false);
        sprite.setEnabled(false);

        Object o = jComboBox1.getItemAt(jComboBox1.getSelectedIndex());

        if (o.equals("Other")) {
            String quantaty = JOptionPane.showInputDialog(null, "enter the quantaty", "ENTER", 3);
            int parseQuantaty = Integer.parseInt(quantaty);

            numberOfSinacolaOrange += parseQuantaty;

        } else if (o.equals("1")) {
            numberOfSinacolaOrange++;

        } else if (o.equals("2")) {
            numberOfSinacolaOrange += 2;

        } else if (o.equals("3")) {
            numberOfSinacolaOrange += 3;

        }
    }//GEN-LAST:event_sinacolaOrangeMouseClicked

    private void fayrouzMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fayrouzMouseClicked
        // TODO add your handling code here:
        cocacola.setEnabled(false);
        sinacolaCoca.setEnabled(false);
        fanta.setEnabled(false);
        maxCola.setEnabled(false);
        sinacolaApple.setEnabled(false);
        sinacolaOrange.setEnabled(false);
        sprite.setEnabled(false);

        Object o = jComboBox1.getItemAt(jComboBox1.getSelectedIndex());

        if (o.equals("Other")) {
            String quantaty = JOptionPane.showInputDialog(null, "enter the quantaty", "ENTER", 3);
            int parseQuantaty = Integer.parseInt(quantaty);

            numberOfFayrouz += parseQuantaty;

        } else if (o.equals("1")) {
            numberOfFayrouz++;

        } else if (o.equals("2")) {
            numberOfFayrouz += 2;

        } else if (o.equals("3")) {
            numberOfFayrouz += 3;

        }
    }//GEN-LAST:event_fayrouzMouseClicked

    private void spriteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spriteMouseClicked
        // TODO add your handling code here:
        cocacola.setEnabled(false);
        sinacolaCoca.setEnabled(false);
        fanta.setEnabled(false);
        maxCola.setEnabled(false);
        sinacolaApple.setEnabled(false);
        sinacolaOrange.setEnabled(false);
        fayrouz.setEnabled(false);

        Object o = jComboBox1.getItemAt(jComboBox1.getSelectedIndex());

        if (o.equals("Other")) {
            String quantaty = JOptionPane.showInputDialog(null, "enter the quantaty", "ENTER", 3);
            int parseQuantaty = Integer.parseInt(quantaty);

            numberOfSprite += parseQuantaty;

        } else if (o.equals("1")) {
            numberOfSprite++;

        } else if (o.equals("2")) {
            numberOfSprite += 2;

        } else if (o.equals("3")) {
            numberOfSprite += 3;

        }
    }//GEN-LAST:event_spriteMouseClicked

    private void backToMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMainActionPerformed
        // TODO add your handling code here:
        Main m = new Main();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backToMainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buyingFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buyingFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buyingFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buyingFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new buyingFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToMain;
    private javax.swing.JLabel background;
    private javax.swing.JToggleButton cocacola;
    private javax.swing.JButton done;
    private javax.swing.JToggleButton fanta;
    private javax.swing.JToggleButton fayrouz;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JToggleButton maxCola;
    private javax.swing.JToggleButton sinacolaApple;
    private javax.swing.JToggleButton sinacolaCoca;
    private javax.swing.JToggleButton sinacolaOrange;
    private javax.swing.JToggleButton sprite;
    // End of variables declaration//GEN-END:variables
}
