/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package library;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import static library.ViewBooks.jTable1;

/**
 *
 * @author DELL
 */
public class db extends javax.swing.JFrame {

    /**
     * Creates new form db
     */
    public db() {
        initComponents();
        jTable1.setAutoCreateRowSorter(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jScrollPane1.setBackground(new java.awt.Color(153, 102, 0));

        jTable1.setBackground(new java.awt.Color(153, 102, 0));
        jTable1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Password", "Email", "Address", "City", "contact"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 60, 740, 260);

        jButton1.setBackground(new java.awt.Color(153, 102, 0));
        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(500, 580, 110, 40);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 350, 30, 22);

        jTextField1.setBackground(new java.awt.Color(153, 102, 0));
        jTextField1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(170, 350, 200, 30);

        jButton5.setBackground(new java.awt.Color(153, 102, 0));
        jButton5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("→");
        jButton5.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton5KeyPressed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(930, 0, 50, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 430, 51, 22);

        jTextField2.setBackground(new java.awt.Color(153, 102, 0));
        jTextField2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(170, 430, 200, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 470, 90, 22);

        jTextField3.setBackground(new java.awt.Color(153, 102, 0));
        jTextField3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(170, 470, 200, 30);

        jTextField9.setBackground(new java.awt.Color(153, 102, 0));
        jTextField9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(255, 255, 255));
        jTextField9.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField9KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField9);
        jTextField9.setBounds(330, 530, 230, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(430, 430, 60, 22);

        jTextField4.setBackground(new java.awt.Color(153, 102, 0));
        jTextField4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(520, 430, 200, 30);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library/password.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(20, 460, 40, 40);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library/name.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 420, 40, 40);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("City");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 390, 40, 22);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("View Librarian");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(310, 20, 190, 28);

        jTextField5.setBackground(new java.awt.Color(153, 102, 0));
        jTextField5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(170, 390, 200, 30);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Contact");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(430, 390, 80, 22);

        jTextField6.setBackground(new java.awt.Color(153, 102, 0));
        jTextField6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        jTextField6.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField6KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField6);
        jTextField6.setBounds(520, 390, 200, 30);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library/contact.png"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(380, 380, 40, 40);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library/search.jpg"))); // NOI18N
        getContentPane().add(jLabel18);
        jLabel18.setBounds(200, 520, 40, 40);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library/ID.png"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(20, 340, 40, 40);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library/email.png"))); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(380, 420, 40, 40);

        jButton8.setBackground(new java.awt.Color(153, 102, 0));
        jButton8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("→");
        jButton8.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(710, 0, 50, 30);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library/city.png"))); // NOI18N
        getContentPane().add(jLabel17);
        jLabel17.setBounds(20, 380, 40, 40);

        jButton2.setBackground(new java.awt.Color(153, 102, 0));
        jButton2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library/save.jpg"))); // NOI18N
        jButton2.setText("Save");
        jButton2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(200, 580, 110, 40);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library/address.png"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(380, 340, 40, 40);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Address");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(430, 350, 90, 22);

        jTextField7.setBackground(new java.awt.Color(153, 102, 0));
        jTextField7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(255, 255, 255));
        jTextField7.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField7KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField7);
        jTextField7.setBounds(520, 350, 200, 30);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Search:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(250, 530, 70, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library/view books.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 780, 680);

        setSize(new java.awt.Dimension(775, 717));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new AdminSection().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int row = jTable1.getSelectedRow();

        try {
            int id = Integer.parseInt(jTextField1.getText().trim());
            String name = jTextField2.getText().trim();
            String password = jTextField3.getText().trim();
            String email = jTextField4.getText().trim();
            String address = jTextField7.getText().trim();
            String city = jTextField5.getText().trim();
            String contact = jTextField6.getText().trim();
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection c = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "system", "123");
            String sql = "update librarian set id = ?, name = ?, password = ?, email = ?, address = ?, city = ?, num = ? where id = ?";
            PreparedStatement s = c.prepareStatement(sql);
            s.setInt(1, id);
            s.setString(2, name);
            s.setString(3, password);
            s.setString(4, email);
            s.setString(5, address);
            s.setString(6, city);
            s.setString(7, contact);
            s.setString(8, jTable1.getValueAt(row, 0).toString());
            jTable1.setValueAt(id, row, 0);
            jTable1.setValueAt(name, row, 1);
            jTable1.setValueAt(password, row, 2);
            jTable1.setValueAt(email, row, 3);
            jTable1.setValueAt(address, row, 4);
            jTable1.setValueAt(city, row, 5);
            jTable1.setValueAt(contact, row, 6);
            s.executeQuery();

            JOptionPane.showMessageDialog(null, "information updated succefully", "success", 0, new ImageIcon("OIP_2.png"));

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(),"invalid",0,new ImageIcon("R.png"));
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int row = jTable1.getSelectedRow();

        jTextField1.setText(jTable1.getValueAt(row, 0).toString());
        jTextField2.setText(jTable1.getValueAt(row, 1).toString());
        jTextField3.setText(jTable1.getValueAt(row, 2).toString());
        jTextField4.setText(jTable1.getValueAt(row, 3).toString());
        jTextField5.setText(jTable1.getValueAt(row, 5).toString());
        jTextField6.setText(jTable1.getValueAt(row, 6).toString());
        jTextField7.setText(jTable1.getValueAt(row, 4).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            int row = jTable1.getSelectedRow();

            try {
                int id = Integer.parseInt(jTextField1.getText().trim());
                String name = jTextField2.getText().trim();
                String password = jTextField3.getText().trim();
                String email = jTextField4.getText().trim();
                String address = jTextField7.getText().trim();
                String city = jTextField5.getText().trim();
                String contact = jTextField6.getText().trim();
                Class.forName("oracle.jdbc.driver.OracleDriver");
                Connection c = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "system", "123");
                String sql = "update librarian set id = ?, name = ?, password = ?, email = ?, address = ?, city = ?, num = ? where id = ?";
                PreparedStatement s = c.prepareStatement(sql);
                s.setInt(1, id);
                s.setString(2, name);
                s.setString(3, password);
                s.setString(4, email);
                s.setString(5, address);
                s.setString(6, city);
                s.setString(7, contact);
                s.setString(8, jTable1.getValueAt(row, 0).toString());
                jTable1.setValueAt(id, row, 0);
                jTable1.setValueAt(name, row, 1);
                jTable1.setValueAt(password, row, 2);
                jTable1.setValueAt(email, row, 3);
                jTable1.setValueAt(address, row, 4);
                jTable1.setValueAt(city, row, 5);
                jTable1.setValueAt(contact, row, 6);
                s.executeQuery();

                JOptionPane.showMessageDialog(null, "information updated succefully", "success", 0, new ImageIcon("OIP_2.png"));

            } catch (ClassNotFoundException | SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(),"invalid",0,new ImageIcon("R.png"));
            }
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            int row = jTable1.getSelectedRow();

            try {
                int id = Integer.parseInt(jTextField1.getText().trim());
                String name = jTextField2.getText().trim();
                String password = jTextField3.getText().trim();
                String email = jTextField4.getText().trim();
                String address = jTextField7.getText().trim();
                String city = jTextField5.getText().trim();
                String contact = jTextField6.getText().trim();
                Class.forName("oracle.jdbc.driver.OracleDriver");
                Connection c = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "system", "123");
                String sql = "update librarian set id = ?, name = ?, password = ?, email = ?, address = ?, city = ?, num = ? where id = ?";
                PreparedStatement s = c.prepareStatement(sql);
                s.setInt(1, id);
                s.setString(2, name);
                s.setString(3, password);
                s.setString(4, email);
                s.setString(5, address);
                s.setString(6, city);
                s.setString(7, contact);
                s.setString(8, jTable1.getValueAt(row, 0).toString());
                jTable1.setValueAt(id, row, 0);
                jTable1.setValueAt(name, row, 1);
                jTable1.setValueAt(password, row, 2);
                jTable1.setValueAt(email, row, 3);
                jTable1.setValueAt(address, row, 4);
                jTable1.setValueAt(city, row, 5);
                jTable1.setValueAt(contact, row, 6);
                s.executeQuery();

                JOptionPane.showMessageDialog(null, "information updated succefully", "success", 0, new ImageIcon("OIP_2.png"));

            } catch (ClassNotFoundException | SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(),"invalid",0,new ImageIcon("R.png"));
            }
        }
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            int row = jTable1.getSelectedRow();

            try {
                int id = Integer.parseInt(jTextField1.getText().trim());
                String name = jTextField2.getText().trim();
                String password = jTextField3.getText().trim();
                String email = jTextField4.getText().trim();
                String address = jTextField7.getText().trim();
                String city = jTextField5.getText().trim();
                String contact = jTextField6.getText().trim();
                Class.forName("oracle.jdbc.driver.OracleDriver");
                Connection c = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "system", "123");
                String sql = "update librarian set id = ?, name = ?, password = ?, email = ?, address = ?, city = ?, num = ? where id = ?";
                PreparedStatement s = c.prepareStatement(sql);
                s.setInt(1, id);
                s.setString(2, name);
                s.setString(3, password);
                s.setString(4, email);
                s.setString(5, address);
                s.setString(6, city);
                s.setString(7, contact);
                s.setString(8, jTable1.getValueAt(row, 0).toString());
                jTable1.setValueAt(id, row, 0);
                jTable1.setValueAt(name, row, 1);
                jTable1.setValueAt(password, row, 2);
                jTable1.setValueAt(email, row, 3);
                jTable1.setValueAt(address, row, 4);
                jTable1.setValueAt(city, row, 5);
                jTable1.setValueAt(contact, row, 6);
                s.executeQuery();

                JOptionPane.showMessageDialog(null, "information updated succefully", "success", 0, new ImageIcon("OIP_2.png"));

            } catch (ClassNotFoundException | SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(),"invalid",0,new ImageIcon("R.png"));
            }
        }
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            int row = jTable1.getSelectedRow();

            try {
                int id = Integer.parseInt(jTextField1.getText().trim());
                String name = jTextField2.getText().trim();
                String password = jTextField3.getText().trim();
                String email = jTextField4.getText().trim();
                String address = jTextField7.getText().trim();
                String city = jTextField5.getText().trim();
                String contact = jTextField6.getText().trim();
                Class.forName("oracle.jdbc.driver.OracleDriver");
                Connection c = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "system", "123");
                String sql = "update librarian set id = ?, name = ?, password = ?, email = ?, address = ?, city = ?, num = ? where id = ?";
                PreparedStatement s = c.prepareStatement(sql);
                s.setInt(1, id);
                s.setString(2, name);
                s.setString(3, password);
                s.setString(4, email);
                s.setString(5, address);
                s.setString(6, city);
                s.setString(7, contact);
                s.setString(8, jTable1.getValueAt(row, 0).toString());
                jTable1.setValueAt(id, row, 0);
                jTable1.setValueAt(name, row, 1);
                jTable1.setValueAt(password, row, 2);
                jTable1.setValueAt(email, row, 3);
                jTable1.setValueAt(address, row, 4);
                jTable1.setValueAt(city, row, 5);
                jTable1.setValueAt(contact, row, 6);
                s.executeQuery();

                JOptionPane.showMessageDialog(null, "information updated succefully", "success", 0, new ImageIcon("OIP_2.png"));

            } catch (ClassNotFoundException | SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(),"invalid",0,new ImageIcon("R.png"));
            }
        }
    }//GEN-LAST:event_jTextField4KeyPressed

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            int row = jTable1.getSelectedRow();

            try {
                int id = Integer.parseInt(jTextField1.getText().trim());
                String name = jTextField2.getText().trim();
                String password = jTextField3.getText().trim();
                String email = jTextField4.getText().trim();
                String address = jTextField7.getText().trim();
                String city = jTextField5.getText().trim();
                String contact = jTextField6.getText().trim();
                Class.forName("oracle.jdbc.driver.OracleDriver");
                Connection c = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "system", "123");
                String sql = "update librarian set id = ?, name = ?, password = ?, email = ?, address = ?, city = ?, num = ? where id = ?";
                PreparedStatement s = c.prepareStatement(sql);
                s.setInt(1, id);
                s.setString(2, name);
                s.setString(3, password);
                s.setString(4, email);
                s.setString(5, address);
                s.setString(6, city);
                s.setString(7, contact);
                s.setString(8, jTable1.getValueAt(row, 0).toString());
                jTable1.setValueAt(id, row, 0);
                jTable1.setValueAt(name, row, 1);
                jTable1.setValueAt(password, row, 2);
                jTable1.setValueAt(email, row, 3);
                jTable1.setValueAt(address, row, 4);
                jTable1.setValueAt(city, row, 5);
                jTable1.setValueAt(contact, row, 6);
                s.executeQuery();

                JOptionPane.showMessageDialog(null, "information updated succefully", "success", 0, new ImageIcon("OIP_2.png"));

            } catch (ClassNotFoundException | SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(),"invalid",0,new ImageIcon("R.png"));
            }
        }
    }//GEN-LAST:event_jTextField5KeyPressed

    private void jTextField7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            int row = jTable1.getSelectedRow();

            try {
                int id = Integer.parseInt(jTextField1.getText().trim());
                String name = jTextField2.getText().trim();
                String password = jTextField3.getText().trim();
                String email = jTextField4.getText().trim();
                String address = jTextField7.getText().trim();
                String city = jTextField5.getText().trim();
                String contact = jTextField6.getText().trim();
                Class.forName("oracle.jdbc.driver.OracleDriver");
                Connection c = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "system", "123");
                String sql = "update librarian set id = ?, name = ?, password = ?, email = ?, address = ?, city = ?, num = ? where id = ?";
                PreparedStatement s = c.prepareStatement(sql);
                s.setInt(1, id);
                s.setString(2, name);
                s.setString(3, password);
                s.setString(4, email);
                s.setString(5, address);
                s.setString(6, city);
                s.setString(7, contact);
                s.setString(8, jTable1.getValueAt(row, 0).toString());
                jTable1.setValueAt(id, row, 0);
                jTable1.setValueAt(name, row, 1);
                jTable1.setValueAt(password, row, 2);
                jTable1.setValueAt(email, row, 3);
                jTable1.setValueAt(address, row, 4);
                jTable1.setValueAt(city, row, 5);
                jTable1.setValueAt(contact, row, 6);
                s.executeQuery();

                JOptionPane.showMessageDialog(null, "information updated succefully", "success", 0, new ImageIcon("OIP_2.png"));

            } catch (ClassNotFoundException | SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(),"invalid",0,new ImageIcon("R.png"));
            }
        }
    }//GEN-LAST:event_jTextField7KeyPressed

    private void jTextField6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            int row = jTable1.getSelectedRow();

            try {
                int id = Integer.parseInt(jTextField1.getText().trim());
                String name = jTextField2.getText().trim();
                String password = jTextField3.getText().trim();
                String email = jTextField4.getText().trim();
                String address = jTextField7.getText().trim();
                String city = jTextField5.getText().trim();
                String contact = jTextField6.getText().trim();
                Class.forName("oracle.jdbc.driver.OracleDriver");
                Connection c = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "system", "123");
                String sql = "update librarian set id = ?, name = ?, password = ?, email = ?, address = ?, city = ?, num = ? where id = ?";
                PreparedStatement s = c.prepareStatement(sql);
                s.setInt(1, id);
                s.setString(2, name);
                s.setString(3, password);
                s.setString(4, email);
                s.setString(5, address);
                s.setString(6, city);
                s.setString(7, contact);
                s.setString(8, jTable1.getValueAt(row, 0).toString());
                jTable1.setValueAt(id, row, 0);
                jTable1.setValueAt(name, row, 1);
                jTable1.setValueAt(password, row, 2);
                jTable1.setValueAt(email, row, 3);
                jTable1.setValueAt(address, row, 4);
                jTable1.setValueAt(city, row, 5);
                jTable1.setValueAt(contact, row, 6);
                s.executeQuery();

                JOptionPane.showMessageDialog(null, "information updated succefully", "success", 0, new ImageIcon("OIP_2.png"));

            } catch (ClassNotFoundException | SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(),"invalid",0,new ImageIcon("R.png"));
            }
        }
    }//GEN-LAST:event_jTextField6KeyPressed

    private void jTextField9KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyReleased
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        jTable1.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(jTextField9.getText()));
    }//GEN-LAST:event_jTextField9KeyReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new AdminLogin().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton5KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5KeyPressed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new AdminSection().setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(db.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(db.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(db.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(db.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new db().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
