/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package library;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class librarianResetPassword extends javax.swing.JFrame {

    /**
     * Creates new form resetPassword
     */
    public librarianResetPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Reset Password");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 20, 210, 28);

        jTextField1.setBackground(new java.awt.Color(153, 102, 0));
        jTextField1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(270, 90, 220, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library/name.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(40, 80, 40, 40);

        jTextField2.setBackground(new java.awt.Color(153, 102, 0));
        jTextField2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(270, 140, 220, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ID:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(90, 140, 60, 22);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 90, 60, 22);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("New Password:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 180, 150, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Confirm password:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 230, 170, 22);

        jToggleButton2.setBackground(new java.awt.Color(153, 102, 0));
        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library/eye2.png"))); // NOI18N
        jToggleButton2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jToggleButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton2MouseClicked(evt);
            }
        });
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jToggleButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jToggleButton2KeyPressed(evt);
            }
        });
        getContentPane().add(jToggleButton2);
        jToggleButton2.setBounds(510, 180, 50, 30);

        jToggleButton1.setBackground(new java.awt.Color(153, 102, 0));
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library/eye2.png"))); // NOI18N
        jToggleButton1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseClicked(evt);
            }
        });
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jToggleButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jToggleButton1KeyPressed(evt);
            }
        });
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(510, 230, 50, 30);

        jButton3.setBackground(new java.awt.Color(153, 102, 0));
        jButton3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library/save.jpg"))); // NOI18N
        jButton3.setText("Save");
        jButton3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(380, 330, 100, 40);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library/password.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(40, 220, 40, 40);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library/ID.png"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(40, 130, 40, 40);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library/password.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(40, 170, 40, 40);

        jPasswordField1.setBackground(new java.awt.Color(153, 102, 0));
        jPasswordField1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(270, 230, 220, 30);

        jPasswordField2.setBackground(new java.awt.Color(153, 102, 0));
        jPasswordField2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPasswordField2.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jPasswordField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField2KeyPressed(evt);
            }
        });
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(270, 180, 220, 30);

        jButton1.setBackground(new java.awt.Color(153, 102, 0));
        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Clear");
        jButton1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(150, 330, 100, 40);

        jButton2.setBackground(new java.awt.Color(153, 102, 0));
        jButton2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("→");
        jButton2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(540, 0, 50, 30);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library/new.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 590, 440);

        setSize(new java.awt.Dimension(602, 457));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField2.setText("");
        jPasswordField1.setText("");
        jPasswordField2.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new LibrarianLogin().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String name = jTextField1.getText().trim();
        int id = Integer.parseInt(jTextField2.getText());
        char pass[] = jPasswordField1.getPassword();
        String parse = String.valueOf(pass);
        char confirmPass[] = jPasswordField1.getPassword();
        String confirmParse = String.valueOf(pass);
        if (parse.length() < 8) {
            JOptionPane.showMessageDialog(null, "Password must contain more than 7 characters","Invalid",0,  new ImageIcon("R.png"));
        } else {
            if (confirmParse.equals(parse)) {
                try {

                    Class.forName("oracle.jdbc.driver.OracleDriver");
                    Connection c = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "system", "123");
                    String sql = "select name from librarian where name = ? and id = ?";
                    PreparedStatement s = c.prepareStatement(sql);
                    s.setString(1, name);
                    s.setInt(2, id);
                    ResultSet rs = s.executeQuery();
                    if (rs.next()) {
                        sql = "update librarian set password = ? where name = ?";
                        s = c.prepareStatement(sql);
                        s.setString(1, parse);
                        s.setString(2, name);
                        s.executeQuery();
                        JOptionPane.showMessageDialog(null, "password changed succefully","success",0,  new ImageIcon("OIP_2.png"));
                    } else {
                        JOptionPane.showMessageDialog(null, "invalid username or ID","invalid",0,  new ImageIcon("R.png"));
                    }
                    rs.close();
                    s.close();
                    c.close();

                } catch (ClassNotFoundException | SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage(),"invalid",0,new ImageIcon("R.png"));
                }
            } else {
                JOptionPane.showMessageDialog(null, "The two passwords doesn't match","invalid",0,new ImageIcon("R.png"));
            }
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jToggleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jToggleButton1MouseClicked

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        if (jToggleButton1.isSelected()) {
            jToggleButton1.setIcon(new ImageIcon("eye1.png"));
            jPasswordField1.setEchoChar((char) 0);
        } else {
            jToggleButton1.setIcon(new ImageIcon("eye2.png"));
            jPasswordField1.setEchoChar('*');
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton2MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jToggleButton2MouseClicked

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        if (jToggleButton2.isSelected()) {
            jToggleButton2.setIcon(new ImageIcon("eye1.png"));
            jPasswordField2.setEchoChar((char) 0);
        } else {
            jToggleButton2.setIcon(new ImageIcon("eye2.png"));
            jPasswordField2.setEchoChar('*');
        }
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String name = jTextField1.getText().trim();
            int id = Integer.parseInt(jTextField2.getText());
            char pass[] = jPasswordField1.getPassword();
            String parse = String.valueOf(pass);
            char confirmPass[] = jPasswordField1.getPassword();
            String confirmParse = String.valueOf(pass);
            if (parse.length() < 8) {
                JOptionPane.showMessageDialog(null, "Password must contain more than 7 characters","invalid",0,  new ImageIcon("R.png"));
            } else {
                if (confirmParse.equals(parse)) {
                    try {

                        Class.forName("oracle.jdbc.driver.OracleDriver");
                        Connection c = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "system", "123");
                        String sql = "select name from librarian where name = ? and id = ?";
                        PreparedStatement s = c.prepareStatement(sql);
                        s.setString(1, name);
                        s.setInt(2, id);
                        ResultSet rs = s.executeQuery();
                        if (rs.next()) {
                            sql = "update librarian set password = ? where name = ?";
                            s = c.prepareStatement(sql);
                            s.setString(1, parse);
                            s.setString(2, name);
                            s.executeQuery();
                            JOptionPane.showMessageDialog(null, "password changed succefully","success",0,  new ImageIcon("OIP_2.png"));
                        } else {
                            JOptionPane.showMessageDialog(null, "invalid username or ID","invalid",0,  new ImageIcon("R.png"));
                        }
                        rs.close();
                        s.close();
                        c.close();

                    } catch (ClassNotFoundException | SQLException ex) {
                        JOptionPane.showMessageDialog(null, ex.getMessage(),"invalid",0,new ImageIcon("R.png"));
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "The two passwords doesn't match","invalid",0,  new ImageIcon("R.png"));
                }
            }
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String name = jTextField1.getText().trim();
            int id = Integer.parseInt(jTextField2.getText());
            char pass[] = jPasswordField1.getPassword();
            String parse = String.valueOf(pass);
            char confirmPass[] = jPasswordField1.getPassword();
            String confirmParse = String.valueOf(pass);
            if (parse.length() < 8) {
                JOptionPane.showMessageDialog(null, "Password must contain more than 7 characters","invalid",0,  new ImageIcon("R.png"));
            } else {
                if (confirmParse.equals(parse)) {
                    try {

                        Class.forName("oracle.jdbc.driver.OracleDriver");
                        Connection c = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "system", "123");
                        String sql = "select name from librarian where name = ? and id = ?";
                        PreparedStatement s = c.prepareStatement(sql);
                        s.setString(1, name);
                        s.setInt(2, id);
                        ResultSet rs = s.executeQuery();
                        if (rs.next()) {
                            sql = "update librarian set password = ? where name = ?";
                            s = c.prepareStatement(sql);
                            s.setString(1, parse);
                            s.setString(2, name);
                            s.executeQuery();
                            JOptionPane.showMessageDialog(null, "password changed succefully","success",0,  new ImageIcon("OIP_2.png"));
                        } else {
                            JOptionPane.showMessageDialog(null, "invalid username or ID","invalid",0,  new ImageIcon("R.png"));
                        }
                        rs.close();
                        s.close();
                        c.close();

                    } catch (ClassNotFoundException | SQLException ex) {
                        JOptionPane.showMessageDialog(null, ex.getMessage(),"invalid",0,new ImageIcon("R.png"));
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "The two passwords doesn't match","invalid",0,  new ImageIcon("R.png"));
                }
            }
        }
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jPasswordField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField2KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String name = jTextField1.getText().trim();
            int id = Integer.parseInt(jTextField2.getText());
            char pass[] = jPasswordField1.getPassword();
            String parse = String.valueOf(pass);
            char confirmPass[] = jPasswordField1.getPassword();
            String confirmParse = String.valueOf(pass);
            if (parse.length() < 8) {
                JOptionPane.showMessageDialog(null, "Password must contain more than 7 characters","invalid",0,  new ImageIcon("R.png"));
            } else {
                if (confirmParse.equals(parse)) {
                    try {

                        Class.forName("oracle.jdbc.driver.OracleDriver");
                        Connection c = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "system", "123");
                        String sql = "select name from librarian where name = ? and id = ?";
                        PreparedStatement s = c.prepareStatement(sql);
                        s.setString(1, name);
                        s.setInt(2, id);
                        ResultSet rs = s.executeQuery();
                        if (rs.next()) {
                            sql = "update librarian set password = ? where name = ?";
                            s = c.prepareStatement(sql);
                            s.setString(1, parse);
                            s.setString(2, name);
                            s.executeQuery();
                            JOptionPane.showMessageDialog(null, "password changed succefully","success",0,  new ImageIcon("OIP_2.png"));
                        } else {
                            JOptionPane.showMessageDialog(null, "invalid username or ID","invalid",0,  new ImageIcon("R.png"));
                        }
                        rs.close();
                        s.close();
                        c.close();

                    } catch (ClassNotFoundException | SQLException ex) {
                        JOptionPane.showMessageDialog(null, ex.getMessage(),"invalid",0,new ImageIcon("R.png"));
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "The two passwords doesn't match","invalid",0,  new ImageIcon("R.png"));
                }
            }
        }
    }//GEN-LAST:event_jPasswordField2KeyPressed

    private void jToggleButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jToggleButton2KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String name = jTextField1.getText().trim();
            int id = Integer.parseInt(jTextField2.getText());
            char pass[] = jPasswordField1.getPassword();
            String parse = String.valueOf(pass);
            char confirmPass[] = jPasswordField1.getPassword();
            String confirmParse = String.valueOf(pass);
            if (parse.length() < 8) {
                JOptionPane.showMessageDialog(null, "Password must contain more than 7 characters","invalid",0,  new ImageIcon("R.png"));
            } else {
                if (confirmParse.equals(parse)) {
                    try {

                        Class.forName("oracle.jdbc.driver.OracleDriver");
                        Connection c = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "system", "123");
                        String sql = "select name from librarian where name = ? and id = ?";
                        PreparedStatement s = c.prepareStatement(sql);
                        s.setString(1, name);
                        s.setInt(2, id);
                        ResultSet rs = s.executeQuery();
                        if (rs.next()) {
                            sql = "update librarian set password = ? where name = ?";
                            s = c.prepareStatement(sql);
                            s.setString(1, parse);
                            s.setString(2, name);
                            s.executeQuery();
                            JOptionPane.showMessageDialog(null, "password changed succefully","success",0,  new ImageIcon("OIP_2.png"));
                        } else {
                            JOptionPane.showMessageDialog(null, "invalid username or ID","invalid",0,  new ImageIcon("R.png"));
                        }
                        rs.close();
                        s.close();
                        c.close();

                    } catch (ClassNotFoundException | SQLException ex) {
                        JOptionPane.showMessageDialog(null, ex.getMessage(),"invalid",0,new ImageIcon("R.png"));
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "The two passwords doesn't match","invalid",0,  new ImageIcon("R.png"));
                }
            }
        }
    }//GEN-LAST:event_jToggleButton2KeyPressed

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String name = jTextField1.getText().trim();
            int id = Integer.parseInt(jTextField2.getText());
            char pass[] = jPasswordField1.getPassword();
            String parse = String.valueOf(pass);
            char confirmPass[] = jPasswordField1.getPassword();
            String confirmParse = String.valueOf(pass);
            if (parse.length() < 8) {
                JOptionPane.showMessageDialog(null, "Password must contain more than 7 characters","invalid",0,  new ImageIcon("R.png"));
            } else {
                if (confirmParse.equals(parse)) {
                    try {

                        Class.forName("oracle.jdbc.driver.OracleDriver");
                        Connection c = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "system", "123");
                        String sql = "select name from librarian where name = ? and id = ?";
                        PreparedStatement s = c.prepareStatement(sql);
                        s.setString(1, name);
                        s.setInt(2, id);
                        ResultSet rs = s.executeQuery();
                        if (rs.next()) {
                            sql = "update librarian set password = ? where name = ?";
                            s = c.prepareStatement(sql);
                            s.setString(1, parse);
                            s.setString(2, name);
                            s.executeQuery();
                            JOptionPane.showMessageDialog(null, "password changed succefully","success",0,  new ImageIcon("OIP_2.png"));
                        } else {
                            JOptionPane.showMessageDialog(null, "invalid username or ID","invalid",0,  new ImageIcon("R.png"));
                        }
                        rs.close();
                        s.close();
                        c.close();

                    } catch (ClassNotFoundException | SQLException ex) {
                        JOptionPane.showMessageDialog(null, ex.getMessage(),"invalid",0,new ImageIcon("R.png"));
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "The two passwords doesn't match","invalid",0,  new ImageIcon("R.png"));
                }
            }
        }
    }//GEN-LAST:event_jPasswordField1KeyPressed

    private void jToggleButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jToggleButton1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String name = jTextField1.getText().trim();
            int id = Integer.parseInt(jTextField2.getText());
            char pass[] = jPasswordField1.getPassword();
            String parse = String.valueOf(pass);
            char confirmPass[] = jPasswordField1.getPassword();
            String confirmParse = String.valueOf(pass);
            if (parse.length() < 8) {
                JOptionPane.showMessageDialog(null, "Password must contain more than 7 characters","invalid",0,  new ImageIcon("R.png"));
            } else {
                if (confirmParse.equals(parse)) {
                    try {

                        Class.forName("oracle.jdbc.driver.OracleDriver");
                        Connection c = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "system", "123");
                        String sql = "select name from librarian where name = ? and id = ?";
                        PreparedStatement s = c.prepareStatement(sql);
                        s.setString(1, name);
                        s.setInt(2, id);
                        ResultSet rs = s.executeQuery();
                        if (rs.next()) {
                            sql = "update librarian set password = ? where name = ?";
                            s = c.prepareStatement(sql);
                            s.setString(1, parse);
                            s.setString(2, name);
                            s.executeQuery();
                            JOptionPane.showMessageDialog(null, "password changed succefully","success",0,  new ImageIcon("OIP_2.png"));
                        } else {
                            JOptionPane.showMessageDialog(null, "invalid username or ID","invalid",0,  new ImageIcon("R.png"));
                        }
                        rs.close();
                        s.close();
                        c.close();

                    } catch (ClassNotFoundException | SQLException ex) {
                        JOptionPane.showMessageDialog(null, ex.getMessage(),"invalid",0,new ImageIcon("R.png"));
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "The two passwords doesn't match","invalid",0,  new ImageIcon("R.png"));
                }
            }
        }
    }//GEN-LAST:event_jToggleButton1KeyPressed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String name = jTextField1.getText().trim();
            int id = Integer.parseInt(jTextField2.getText());
            char pass[] = jPasswordField1.getPassword();
            String parse = String.valueOf(pass);
            char confirmPass[] = jPasswordField1.getPassword();
            String confirmParse = String.valueOf(pass);
            if (parse.length() < 8) {
                JOptionPane.showMessageDialog(null, "Password must contain more than 7 characters","invalid",0,  new ImageIcon("R.png"));
            } else {
                if (confirmParse.equals(parse)) {
                    try {

                        Class.forName("oracle.jdbc.driver.OracleDriver");
                        Connection c = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "system", "123");
                        String sql = "select name from librarian where name = ? and id = ?";
                        PreparedStatement s = c.prepareStatement(sql);
                        s.setString(1, name);
                        s.setInt(2, id);
                        ResultSet rs = s.executeQuery();
                        if (rs.next()) {
                            sql = "update librarian set password = ? where name = ?";
                            s = c.prepareStatement(sql);
                            s.setString(1, parse);
                            s.setString(2, name);
                            s.executeQuery();
                            JOptionPane.showMessageDialog(null, "password changed succefully","success",0,  new ImageIcon("OIP_2.png"));
                        } else {
                            JOptionPane.showMessageDialog(null, "invalid username or ID","invalid",0,  new ImageIcon("R.png"));
                        }
                        rs.close();
                        s.close();
                        c.close();

                    } catch (ClassNotFoundException | SQLException ex) {
                        JOptionPane.showMessageDialog(null, ex.getMessage(),"invalid",0,new ImageIcon("R.png"));
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "The two passwords doesn't match","invalid",0,  new ImageIcon("R.png"));
                }
            }
        }
    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String name = jTextField1.getText().trim();
            int id = Integer.parseInt(jTextField2.getText());
            char pass[] = jPasswordField1.getPassword();
            String parse = String.valueOf(pass);
            char confirmPass[] = jPasswordField1.getPassword();
            String confirmParse = String.valueOf(pass);
            if (parse.length() < 8) {
                JOptionPane.showMessageDialog(null, "Password must contain more than 7 characters","invalid",0,  new ImageIcon("R.png"));
            } else {
                if (confirmParse.equals(parse)) {
                    try {

                        Class.forName("oracle.jdbc.driver.OracleDriver");
                        Connection c = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "system", "123");
                        String sql = "select name from librarian where name = ? and id = ?";
                        PreparedStatement s = c.prepareStatement(sql);
                        s.setString(1, name);
                        s.setInt(2, id);
                        ResultSet rs = s.executeQuery();
                        if (rs.next()) {
                            sql = "update librarian set password = ? where name = ?";
                            s = c.prepareStatement(sql);
                            s.setString(1, parse);
                            s.setString(2, name);
                            s.executeQuery();
                            JOptionPane.showMessageDialog(null, "password changed succefully","success",0,  new ImageIcon("OIP_2.png"));
                        } else {
                            JOptionPane.showMessageDialog(null, "invalid username or ID","invalid",0,  new ImageIcon("R.png"));
                        }
                        rs.close();
                        s.close();
                        c.close();

                    } catch (ClassNotFoundException | SQLException ex) {
                        JOptionPane.showMessageDialog(null, ex.getMessage(),"invalid",0,new ImageIcon("R.png"));
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "The two passwords doesn't match","invalid",0,  new ImageIcon("R.png"));
                }
            }
        }
    }//GEN-LAST:event_jButton2KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(librarianResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(librarianResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(librarianResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(librarianResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new librarianResetPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
